import { useEffect, useState } from 'react'
import { cn } from '@/lib/utils'

/**
 * A reel's cover image. Thumbnails are generated by the video host and are
 * sometimes missing or dead; rather than a broken-image icon, fall back to the
 * video's own first frame, which always exists while the reel does.
 */
export function ReelThumb({ thumbnailUrl, videoUrl, className }: { thumbnailUrl?: string; videoUrl?: string; className?: string }) {
  const [failed, setFailed] = useState(!thumbnailUrl)
  useEffect(() => { setFailed(!thumbnailUrl) }, [thumbnailUrl])
  if (!failed) {
    return <img src={thumbnailUrl} alt="" loading="lazy" draggable={false} onError={() => setFailed(true)} className={cn('object-cover', className)} />
  }
  if (!videoUrl) return <span className={cn('bg-neutral-900', className)} />
  return <video src={`${videoUrl}#t=0.1`} preload="metadata" muted playsInline className={cn('object-cover bg-neutral-900', className)} />
}
