import { motion, useReducedMotion } from 'framer-motion'
import { Link } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { ArrowRight, Check } from 'lucide-react'

export const CTASection = () => {
  const { t } = useTranslation()
  const reduceMotion = useReducedMotion()
  return <section className="bg-[#f2f0e6] px-5 py-20 text-[#102014] sm:px-8 lg:px-12 lg:py-28"><motion.div initial={{ opacity: 0, scale: reduceMotion ? 1 : .97 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true }} transition={{ duration: .7 }} className="relative mx-auto max-w-[1440px] overflow-hidden rounded-[2rem] bg-[#d9ff43] px-7 py-16 sm:px-12 lg:px-20 lg:py-24"><div className="absolute -right-24 -top-24 h-80 w-80 rounded-full border-[70px] border-[#102014]/[.06]" /><div className="relative grid gap-12 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-xs font-extrabold uppercase tracking-[.22em] text-green-800">{t('landing.cta.eyebrow')}</p><h2 className="mt-5 max-w-4xl text-5xl font-semibold leading-[.91] tracking-[-.055em] sm:text-6xl lg:text-8xl" style={{ fontFamily: 'var(--font-display)' }}>{t('landing.cta.title')}</h2><div className="mt-8 flex flex-wrap gap-x-7 gap-y-3 text-sm font-semibold text-black/60"><span className="flex items-center gap-2"><Check className="h-4 w-4" />{t('landing.cta.free')}</span><span className="flex items-center gap-2"><Check className="h-4 w-4" />{t('landing.cta.forBoth')}</span><span className="flex items-center gap-2"><Check className="h-4 w-4" />{t('landing.cta.escrow')}</span></div></div><div className="flex flex-col gap-3 sm:flex-row lg:flex-col"><Link to="/register?intent=sell" className="group flex min-w-56 items-center justify-between gap-4 rounded-full bg-[#102014] px-7 py-4 font-bold text-white">{t('landing.cta.startSelling')} <ArrowRight className="h-5 w-5 transition-transform group-hover:translate-x-1" /></Link><Link to="/register?intent=buy" className="group flex min-w-56 items-center justify-between gap-4 rounded-full border border-[#102014]/25 px-7 py-4 font-bold transition-colors hover:bg-[#102014]/10">{t('landing.cta.startBuying')} <ArrowRight className="h-5 w-5 transition-transform group-hover:translate-x-1" /></Link></div></div></motion.div></section>
}
