import { motion, useReducedMotion } from 'framer-motion'
import { ArrowRight, Building2, MapPin, Package, Timer } from 'lucide-react'
import { Link } from 'react-router-dom'

const requests = [
  { category: 'Fresh produce', title: '5 tonnes of fresh tomatoes', location: 'Dar es Salaam', quantity: 'Weekly delivery', budget: 'TZS 2.1–3.1M', bids: 12, buyer: 'Serena Hotels', urgent: true },
  { category: 'Grains', title: '20 tonnes of organic maize', location: 'Nairobi, Kenya', quantity: 'Monthly supply', budget: 'TZS 10.4–15.6M', bids: 8, buyer: 'EcoGrain Exports', urgent: false },
  { category: 'Export', title: 'Mixed tropical fruit shipment', location: 'Lagos, Nigeria', quantity: '50 tonne lot', budget: 'Open to offers', bids: 23, buyer: 'FreshLink Retail', urgent: true },
]

export const RequirementsShowcase = () => {
  const reduceMotion = useReducedMotion()
  return <section className="bg-[#0d1b13] px-5 py-24 sm:px-8 lg:px-12 lg:py-36"><div className="mx-auto max-w-[1440px]">
    <div className="grid gap-8 lg:grid-cols-[1fr_.7fr] lg:items-end"><motion.div initial={{ opacity: 0, y: reduceMotion ? 0 : 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><p className="text-xs font-extrabold uppercase tracking-[.22em] text-[#d9ff43]">Live buyer demand</p><h2 className="mt-5 text-5xl font-semibold leading-[.94] tracking-[-.05em] sm:text-6xl lg:text-7xl" style={{ fontFamily: 'var(--font-display)' }}>Don't wait for buyers.<br /><span className="text-white/35">See what they need.</span></h2></motion.div><p className="max-w-lg text-lg leading-8 text-white/50 lg:justify-self-end">Real requests from businesses looking for reliable supply. Find the right fit and put your farm forward.</p></div>
    <div className="mt-16 overflow-hidden rounded-[1.75rem] border border-white/10">{requests.map((req, i) => <motion.article key={req.title} initial={{ opacity: 0, x: reduceMotion ? 0 : -24 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: i * .08 }} className="group grid gap-6 border-b border-white/10 bg-white/[.025] p-6 transition-colors last:border-0 hover:bg-white/[.06] md:grid-cols-[1fr_auto] md:items-center lg:p-8"><div><div className="flex flex-wrap items-center gap-3"><span className="rounded-full border border-white/10 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-white/45">{req.category}</span>{req.urgent && <span className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-widest text-[#d9ff43]"><Timer className="h-3.5 w-3.5" /> Closing soon</span>}</div><h3 className="mt-4 text-2xl font-semibold tracking-tight sm:text-3xl">{req.title}</h3><div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-sm text-white/40"><span className="flex items-center gap-1.5"><Building2 className="h-4 w-4" />{req.buyer}</span><span className="flex items-center gap-1.5"><MapPin className="h-4 w-4" />{req.location}</span><span className="flex items-center gap-1.5"><Package className="h-4 w-4" />{req.quantity}</span></div></div><div className="flex items-center gap-8 md:pl-8"><div><p className="text-[10px] font-bold uppercase tracking-widest text-white/30">Budget</p><p className="mt-1 font-bold text-[#d9ff43]">{req.budget}</p></div><div><p className="text-[10px] font-bold uppercase tracking-widest text-white/30">Offers</p><p className="mt-1 font-bold">{req.bids}</p></div><ArrowRight className="h-5 w-5 text-white/20 transition-transform group-hover:translate-x-1 group-hover:text-[#d9ff43]" /></div></motion.article>)}</div>
    <div className="mt-8 flex justify-end"><Link to="/requirements" className="group flex items-center gap-3 rounded-full bg-[#d9ff43] px-6 py-3.5 font-bold text-[#102014]">Browse all requests <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></Link></div>
  </div></section>
}
