import { motion, useReducedMotion } from 'framer-motion'
import { ArrowRight, Building2, MapPin, Package, Timer } from 'lucide-react'
import { Link } from 'react-router-dom'

const requests = [
  { category: 'Fresh produce', title: '5 tonnes of fresh tomatoes', location: 'Dar es Salaam', quantity: 'Weekly delivery', budget: 'TZS 2.1–3.1M', bids: 12, buyer: 'Bahari Hospitality', urgent: true },
  { category: 'Grains', title: '20 tonnes of quality maize', location: 'Arusha, Tanzania', quantity: 'Monthly supply', budget: 'TZS 10.4–15.6M', bids: 8, buyer: 'Kaskazi Foods', urgent: false },
  { category: 'Fresh produce', title: '150kg of spinach & kale, weekly', location: 'Mwanza, Tanzania', quantity: 'Weekly delivery', budget: 'TZS 380K–520K', bids: 6, buyer: 'Green Table Café', urgent: false },
  { category: 'Fresh fruit', title: 'Mixed tropical fruit shipment', location: 'Zanzibar, Tanzania', quantity: '10 tonne lot', budget: 'Open to offers', bids: 23, buyer: 'Pwani Fresh Markets', urgent: true },
]

export const RequirementsShowcase = () => {
  const reduceMotion = useReducedMotion()
  return <section id="buyer-requests" className="bg-[#0d1b13] px-5 py-24 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1440px]">
    <div className="grid gap-8 lg:grid-cols-[1fr_.7fr] lg:items-end"><motion.div initial={{ opacity: 0, y: reduceMotion ? 0 : 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><p className="text-xs font-extrabold uppercase tracking-[.22em] text-[#d9ff43]">Live buyer demand</p><h2 className="mt-5 text-4xl font-semibold leading-[.96] tracking-[-.05em] sm:text-5xl lg:text-6xl" style={{ fontFamily: 'var(--font-display)' }}>Don&apos;t wait for buyers.<br /><span className="text-white/50">See what they need.</span></h2></motion.div><p className="max-w-lg text-lg leading-8 text-white/65 lg:justify-self-end">Buyer-request examples show how businesses publish demand, compare offers and find dependable supply.</p></div>
    <div className="mt-16 overflow-hidden rounded-[1.75rem] border border-white/10">{requests.map((req, i) => <motion.article key={req.title} initial={{ opacity: 0, x: reduceMotion ? 0 : -24 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: i * .08 }} className="grid gap-6 border-b border-white/10 bg-white/[.025] p-6 transition-colors last:border-0 hover:bg-white/[.06] md:grid-cols-[1fr_auto] md:items-center lg:p-8"><div><div className="flex flex-wrap items-center gap-3"><span className="rounded-full border border-white/10 px-3 py-1 text-xs font-bold uppercase tracking-widest text-white/60">{req.category}</span>{req.urgent && <span className="flex items-center gap-1.5 text-xs font-bold uppercase tracking-widest text-[#d9ff43]"><Timer className="h-3.5 w-3.5" /> Closing soon</span>}</div><h3 className="mt-4 text-2xl font-semibold tracking-tight sm:text-3xl">{req.title}</h3><div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-sm text-white/60"><span className="flex items-center gap-1.5"><Building2 className="h-4 w-4" />{req.buyer}</span><span className="flex items-center gap-1.5"><MapPin className="h-4 w-4" />{req.location}</span><span className="flex items-center gap-1.5"><Package className="h-4 w-4" />{req.quantity}</span></div></div><div className="flex flex-wrap items-center gap-6 md:justify-end md:pl-8"><div><p className="text-xs font-bold uppercase tracking-widest text-white/45">Budget</p><p className="mt-1 font-bold text-[#d9ff43]">{req.budget}</p></div><div><p className="text-xs font-bold uppercase tracking-widest text-white/45">Offers</p><p className="mt-1 font-bold">{req.bids}</p></div><Link to="/register?intent=sell" className="group flex items-center gap-2 rounded-full border border-white/15 px-4 py-2.5 text-sm font-bold text-white/75 hover:border-[#d9ff43]/50 hover:text-white">View request <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></Link></div></motion.article>)}</div>
    <div className="mt-8 flex justify-end"><Link to="/register?intent=sell" className="group flex items-center gap-3 rounded-full bg-[#d9ff43] px-6 py-3.5 font-bold text-[#102014]">Find buyer demand <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></Link></div>
  </div></section>
}
